sigma_me:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SIGMA_ME_DB_HOST') }}"
      user: "{{ env_var('SIGMA_ME_DB_USER') }}"
      password: "{{ env_var('SIGMA_ME_DB_PASS') }}"
      role: "{{ env_var('SIGMA_ME_ROLE') }}"
      database: "{{ env_var('SIGMA_ME_DB_NAME') }}"
      warehouse: "{{ env_var('SIGMA_ME_WAREHOUSE') }}"
      schema: "{{ env_var('SIGMA_ME_SCHEMA') }}"
      query_tag: "{{ env_var('SIGMA_ME_QUERY_TAG') }}"
      threads: 1
      keepalives_idle: 0 # default 0, indicating the system default